### ISSUE TITLE
Eigenvalues of field-dependent mass automatically

### ISSUE THREAD

**Issue by sam1995ya** [clwainwright/CosmoTransitions#13]
Hi Max,

In testModel1.py file, you used the manual definition of eigenvalues of the field-dependent mass matrix in 'boson_massSq' function.

Is it possible to use the 'eigvalsh' function from 'scipy'?
I have tried this but I got an error, it seems that is due to the shape of 'X' in some steps which results in a non-square matrix.

Cheers,
Sam

**Comment by sam1995ya** [comment]
Solved.

**Comment by phase-tr** [comment]
Dear Colleague，
I have been struggling to solve the problem, but fail. Could you share me with your solution?
Many thanks

**Comment by subhojitroy93** [comment]
Hi All,

I have encountered exactly a similar problem and stuck to that part. Get the following error message after using "np.linalg.eig" to diagonalize a 3x3 field-dependent matrix under 'bosob_massSq'.
"LinAlgError: Last 2 dimensions of the array must be square"

Could you kindly let me know how you solve that problem?
Many thanks in advance.

Regards,
Subhojit
