### ISSUE TITLE
Issues with critical temperatures and minimum at T=0

### ISSUE THREAD

**Issue by dani8586** [clwainwright/CosmoTransitions#15]
Hello 
I’m trying to use your package CosmoTransition for computing phase transition in some BSM models. However, after having read the documentation and tried a few tests I have some problems, that I try to ask you with two examples.

I’m dealing with a 1D potential and making a cross-checks with a code that I have implemented in Mathematica.

In the file thermal_tunneling_a.py I have set a standard mexican hat potential, line 59, no field dependent mass (all set to zero lines 69-71). If I run the code however instead than getting a minimum at 246.0, I get a minimum at 246.00000381
Is this just a precision error or am I missing some physics?

The second example is more involved, thermal_tunneling_a.py

I have tried to implement the original coleman-weinberg model with a gauged U(1). No potential at tree level, line 59, and field dependent mass as written in lines 59-71. I know that the potential at low and high-temperature should have the form in the figure (light low T, black high T), where the SSB is given by the T=0 loop potential and the symmetry is restored at high temperature.

However, with my implementation in your package I get strange results, e.g calling

findMinimum(T=0)

I get ~1648, which seems weird. I’m sure I’m missing something crucial in the implementation. Please let me know if you can help

Thanks for you time

Daniele

<img width="407" alt="Screen Shot 2019-05-30 at 3 56 03 PM" src="https://user-images.githubusercontent.com/51203032/58638663-a21e3d80-82f5-11e9-9564-bcd04a180b6a.png">

[thermal_tunneling_a.txt](https://github.com/clwainwright/CosmoTransitions/files/3237363/thermal_tunneling_a.txt)
[thermal_tunneling_b.txt](https://github.com/clwainwright/CosmoTransitions/files/3237364/thermal_tunneling_b.txt)

Screen Shot 2019-05-30 at 3.56.03 PM.png

**Comment by DarkKnight6777** [comment]
Can You figured out what happened to the findMinimum(T=0)?

**Comment by dani8586** [comment]
No, at the end no...

**Comment by nblinov** [comment]
The minimum mismatch is just that any numerical minimization has a numerical tolerance. findMinimum uses scipy.optimize.fmin (see generic_potential.py), which has a  default tolerance of 1e-4 (see https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin.html) 

Regarding the second question. I know this is a bit late, but may be it will be helpful to people in the future. Your CT model implements the following potential:
![image](https://user-images.githubusercontent.com/1775226/72742559-9a0a5b00-3b6f-11ea-9cca-76181bd29fe0.png)
As you saw, CT found the correct minimum. I am not sure how you got the potential in your image. 
May be it is the choice of the renormalization conditions? The CW paper specifies 2 and 4 point functions at p=0, whereas CT assumes MSbar renormalization (the choice of c coefficients boson_massSq to be 3/2 - btw these should be different for transverse and longitudinal gauge boson polarizations)

**Comment by dani8586** [comment]
Hi,

thanks for the comment! I actually need to check, but that might be the solution!!

Thanks a lot for your help

Best

Daniele

**Comment by shilpajangid123** [comment]
After reading CT documentation, I understood that scaler masses can be put in masssq in test1model.py file but I am not able to understand how to put w boson and z boson masses and their thermal corrections.

The second thing is I was trying to change m1 and m2 expressions in bosonmasssq in generic potential.py class but there is no change in result for critical and nucleation temperature.

The third is z2 symmetry for the second field is it correct if vev for the second field is considered zero in tree-level potential itself.

it would be a great help. 

thanks
shilpa
