### ISSUE TITLE
raise TypeError( TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer. 

### ISSUE THREAD

**Issue by DarkKnight6777** [clwainwright/CosmoTransitions#23]
[https://github.com/clwainwright/CosmoTransitions/blob/ba3339784f1a91fb23d374467cf83a948509aaa3/cosmoTransitions/pathDeformation.py#L761-L762](float instead of int)
[https://github.com/numpy/numpy/issues/15345#issuecomment-575917093](cosmoTransition issue)

After updating the numpy to the latest version I am facing this problem

**Comment by royxue** [comment]
@DarkKnight6777  will downgrade to older version actually make it work?
