### ISSUE TITLE
Standard Model Case

### ISSUE THREAD

**Issue by sam1995ya** [clwainwright/CosmoTransitions#8]
Hi,

I ran the package for the standard model with top quark, W and Z bosons. The output contains an extra solution which should not exist in the standard model!
Will you help me to understand what is wrong?

Regards,
Sam
![output](https://user-images.githubusercontent.com/36744350/36560624-81282c0c-1826-11e8-9ca0-2ff0f7514d6d.jpg)

**Comment by clwainwright** [comment]
Such spurious phases typically occur whenever you have a boson with a negative mass-squared value. There's a branch cut in the thermal functions at zero mass, and even if we just take the real part (which is what the package does), there's going to be a noticeable kink in the potential function. The best way around this is to include the thermal contributions to the boson mass, and hope that the thermally corrected mass doesn't go negative. Or you could just treat it at as a non-physical artifact of the computation and ignore it. It's a tricky issue. There are a bunch of theoretical problems when working with effective potentials, so you'll have to be careful either way. See e.g. https://arxiv.org/abs/1204.5464 and references therein. Hope that helps!
